import axios from 'axios';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import TrendingCoins from '../components/trending/TrendingCoins';
import CoinsTable from '../components/coins/CoinsTable';
import Link from 'next/link';

export default function Home({ trendingCoins, coins }) {
  return (
    <div>
      <Head>
        <title>Crypto Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TrendingCoins trendingCoins={trendingCoins} />
      <CoinsTable coins={coins} />
      <Link href="/coins">
        <a className={styles.button}>See more coins</a>
      </Link>
    </div>
  );
}

export async function getServerSideProps() {
  const trendingUrl = 'https://api.coingecko.com/api/v3/search/trending';
  const topCoinsUrl =
    'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false&price_change_percentage=24h';

  const [trendingCoinsRes, topCoinsRes] = await Promise.all([
    axios.get(trendingUrl),
    axios.get(topCoinsUrl),
  ]);

  return {
    props: { trendingCoins: trendingCoinsRes.data, coins: topCoinsRes.data },
  };
}
