import axios from 'axios';
import { useState } from 'react';
import Head from 'next/head';
import CoinsTable from '../../components/coins/CoinsTable';

export default function Coins({ coins }) {
  return (
    <div>
      <Head>
        <title>Coins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CoinsTable coins={coins} />
    </div>
  );
}

export async function getServerSideProps() {
  // TODO: Change pagination 🤔
  const pid = 1;
  const url = `https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=${pid}&sparkline=false&price_change_percentage=24h`;
  const res = await axios.get(url);

  return {
    props: { coins: res.data },
  };
}
