import Head from 'next/head';

export default function Coins() {
  return (
    <div>
      <Head>
        <title>Coins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>All Coins</h1>
      </div>
    </div>
  );
}
